language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPosER_FLAGS} --prefer-source --no-interaction

script:
  - vendor/bin/phpunit
